import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/fish"
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-A", "-D", "-s", "main"]

[cursor]
style = "Block"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[window]
decorations = "None"
option_as_alt = "OnlyLeft"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
  { mods = "Alt", key = "Left", chars = "\u001Bb" },
  { mods = "Alt", key = "Right", chars = "\u001Bf" },
  { mods = "Command", key = "Left", chars = "\u001B[H" },
  { mods = "Command", key = "Right", chars = "\u001B[F" },
  { mods = "Alt", key = "D", chars = "\u0017" },
]
